# Generated by Django 5.2 on 2025-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancecode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
