# Generated by Django 5.2 on 2025-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_absencejustification'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencejustification',
            name='justification_type',
            field=models.CharField(choices=[('absence', 'Ausência Total'), ('late_arrival', 'Chegada Tardia')], default='absence', max_length=20),
        ),
    ]
